// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KNNQuery.proto

package com.michael.endPointCoprocessor;

public final class KNNQueryProto {
  private KNNQueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KNNQueryRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double latitude = 1;
    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    // required double longitude = 2;
    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();

    // required int32 k = 3;
    /**
     * <code>required int32 k = 3;</code>
     */
    boolean hasK();
    /**
     * <code>required int32 k = 3;</code>
     */
    int getK();
  }
  /**
   * Protobuf type {@code KNNQueryRequest}
   */
  public static final class KNNQueryRequest extends
      com.google.protobuf.GeneratedMessage
      implements KNNQueryRequestOrBuilder {
    // Use KNNQueryRequest.newBuilder() to construct.
    private KNNQueryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KNNQueryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KNNQueryRequest defaultInstance;
    public static KNNQueryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public KNNQueryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KNNQueryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              k_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.class, com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<KNNQueryRequest> PARSER =
        new com.google.protobuf.AbstractParser<KNNQueryRequest>() {
      public KNNQueryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KNNQueryRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<KNNQueryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double latitude = 1;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    // required double longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // required int32 k = 3;
    public static final int K_FIELD_NUMBER = 3;
    private int k_;
    /**
     * <code>required int32 k = 3;</code>
     */
    public boolean hasK() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 k = 3;</code>
     */
    public int getK() {
      return k_;
    }

    private void initFields() {
      latitude_ = 0D;
      longitude_ = 0D;
      k_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasK()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, k_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, k_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest)) {
        return super.equals(obj);
      }
      com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest other = (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest) obj;

      boolean result = true;
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (Double.doubleToLongBits(getLatitude())    == Double.doubleToLongBits(other.getLatitude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (Double.doubleToLongBits(getLongitude())    == Double.doubleToLongBits(other.getLongitude()));
      }
      result = result && (hasK() == other.hasK());
      if (hasK()) {
        result = result && (getK()
            == other.getK());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getLongitude()));
      }
      if (hasK()) {
        hash = (37 * hash) + K_FIELD_NUMBER;
        hash = (53 * hash) + getK();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KNNQueryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.class, com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.Builder.class);
      }

      // Construct using com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        k_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryRequest_descriptor;
      }

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest getDefaultInstanceForType() {
        return com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.getDefaultInstance();
      }

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest build() {
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest buildPartial() {
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest result = new com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.k_ = k_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest) {
          return mergeFrom((com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest other) {
        if (other == com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasK()) {
          setK(other.getK());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasK()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double latitude = 1;
      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // required double longitude = 2;
      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // required int32 k = 3;
      private int k_ ;
      /**
       * <code>required int32 k = 3;</code>
       */
      public boolean hasK() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 k = 3;</code>
       */
      public int getK() {
        return k_;
      }
      /**
       * <code>required int32 k = 3;</code>
       */
      public Builder setK(int value) {
        bitField0_ |= 0x00000004;
        k_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 k = 3;</code>
       */
      public Builder clearK() {
        bitField0_ = (bitField0_ & ~0x00000004);
        k_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KNNQueryRequest)
    }

    static {
      defaultInstance = new KNNQueryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KNNQueryRequest)
  }

  public interface KNNQueryResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated double latitude = 1;
    /**
     * <code>repeated double latitude = 1;</code>
     */
    java.util.List<Double> getLatitudeList();
    /**
     * <code>repeated double latitude = 1;</code>
     */
    int getLatitudeCount();
    /**
     * <code>repeated double latitude = 1;</code>
     */
    double getLatitude(int index);

    // repeated double longitude = 2;
    /**
     * <code>repeated double longitude = 2;</code>
     */
    java.util.List<Double> getLongitudeList();
    /**
     * <code>repeated double longitude = 2;</code>
     */
    int getLongitudeCount();
    /**
     * <code>repeated double longitude = 2;</code>
     */
    double getLongitude(int index);
  }
  /**
   * Protobuf type {@code KNNQueryResponse}
   */
  public static final class KNNQueryResponse extends
      com.google.protobuf.GeneratedMessage
      implements KNNQueryResponseOrBuilder {
    // Use KNNQueryResponse.newBuilder() to construct.
    private KNNQueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KNNQueryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KNNQueryResponse defaultInstance;
    public static KNNQueryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public KNNQueryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KNNQueryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                latitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              latitude_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                latitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                latitude_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                longitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              longitude_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                longitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                longitude_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          latitude_ = java.util.Collections.unmodifiableList(latitude_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          longitude_ = java.util.Collections.unmodifiableList(longitude_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.class, com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<KNNQueryResponse> PARSER =
        new com.google.protobuf.AbstractParser<KNNQueryResponse>() {
      public KNNQueryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KNNQueryResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<KNNQueryResponse> getParserForType() {
      return PARSER;
    }

    // repeated double latitude = 1;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private java.util.List<Double> latitude_;
    /**
     * <code>repeated double latitude = 1;</code>
     */
    public java.util.List<Double>
        getLatitudeList() {
      return latitude_;
    }
    /**
     * <code>repeated double latitude = 1;</code>
     */
    public int getLatitudeCount() {
      return latitude_.size();
    }
    /**
     * <code>repeated double latitude = 1;</code>
     */
    public double getLatitude(int index) {
      return latitude_.get(index);
    }

    // repeated double longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private java.util.List<Double> longitude_;
    /**
     * <code>repeated double longitude = 2;</code>
     */
    public java.util.List<Double>
        getLongitudeList() {
      return longitude_;
    }
    /**
     * <code>repeated double longitude = 2;</code>
     */
    public int getLongitudeCount() {
      return longitude_.size();
    }
    /**
     * <code>repeated double longitude = 2;</code>
     */
    public double getLongitude(int index) {
      return longitude_.get(index);
    }

    private void initFields() {
      latitude_ = java.util.Collections.emptyList();
      longitude_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < latitude_.size(); i++) {
        output.writeDouble(1, latitude_.get(i));
      }
      for (int i = 0; i < longitude_.size(); i++) {
        output.writeDouble(2, longitude_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getLatitudeList().size();
        size += dataSize;
        size += 1 * getLatitudeList().size();
      }
      {
        int dataSize = 0;
        dataSize = 8 * getLongitudeList().size();
        size += dataSize;
        size += 1 * getLongitudeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse)) {
        return super.equals(obj);
      }
      com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse other = (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse) obj;

      boolean result = true;
      result = result && getLatitudeList()
          .equals(other.getLatitudeList());
      result = result && getLongitudeList()
          .equals(other.getLongitudeList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getLatitudeCount() > 0) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLatitudeList().hashCode();
      }
      if (getLongitudeCount() > 0) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLongitudeList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KNNQueryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.class, com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.Builder.class);
      }

      // Construct using com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.michael.endPointCoprocessor.KNNQueryProto.internal_static_KNNQueryResponse_descriptor;
      }

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse getDefaultInstanceForType() {
        return com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance();
      }

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse build() {
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse buildPartial() {
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse result = new com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          latitude_ = java.util.Collections.unmodifiableList(latitude_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.latitude_ = latitude_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          longitude_ = java.util.Collections.unmodifiableList(longitude_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse) {
          return mergeFrom((com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse other) {
        if (other == com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance()) return this;
        if (!other.latitude_.isEmpty()) {
          if (latitude_.isEmpty()) {
            latitude_ = other.latitude_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLatitudeIsMutable();
            latitude_.addAll(other.latitude_);
          }
          onChanged();
        }
        if (!other.longitude_.isEmpty()) {
          if (longitude_.isEmpty()) {
            longitude_ = other.longitude_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLongitudeIsMutable();
            longitude_.addAll(other.longitude_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated double latitude = 1;
      private java.util.List<Double> latitude_ = java.util.Collections.emptyList();
      private void ensureLatitudeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          latitude_ = new java.util.ArrayList<Double>(latitude_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public java.util.List<Double>
          getLatitudeList() {
        return java.util.Collections.unmodifiableList(latitude_);
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public int getLatitudeCount() {
        return latitude_.size();
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public double getLatitude(int index) {
        return latitude_.get(index);
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder setLatitude(
          int index, double value) {
        ensureLatitudeIsMutable();
        latitude_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder addLatitude(double value) {
        ensureLatitudeIsMutable();
        latitude_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder addAllLatitude(
          Iterable<? extends Double> values) {
        ensureLatitudeIsMutable();
        super.addAll(values, latitude_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        latitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated double longitude = 2;
      private java.util.List<Double> longitude_ = java.util.Collections.emptyList();
      private void ensureLongitudeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          longitude_ = new java.util.ArrayList<Double>(longitude_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public java.util.List<Double>
          getLongitudeList() {
        return java.util.Collections.unmodifiableList(longitude_);
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public int getLongitudeCount() {
        return longitude_.size();
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public double getLongitude(int index) {
        return longitude_.get(index);
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder setLongitude(
          int index, double value) {
        ensureLongitudeIsMutable();
        longitude_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder addLongitude(double value) {
        ensureLongitudeIsMutable();
        longitude_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder addAllLongitude(
          Iterable<? extends Double> values) {
        ensureLongitudeIsMutable();
        super.addAll(values, longitude_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        longitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KNNQueryResponse)
    }

    static {
      defaultInstance = new KNNQueryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KNNQueryResponse)
  }

  /**
   * Protobuf service {@code KNNQueryService}
   */
  public static abstract class KNNQueryService
      implements com.google.protobuf.Service {
    protected KNNQueryService() {}

    public interface Interface {
      /**
       * <code>rpc getKNNQuery(.KNNQueryRequest) returns (.KNNQueryResponse);</code>
       */
      public abstract void getKNNQuery(
              com.google.protobuf.RpcController controller,
              com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest request,
              com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new KNNQueryService() {
        @Override
        public  void getKNNQuery(
            com.google.protobuf.RpcController controller,
            com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest request,
            com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse> done) {
          impl.getKNNQuery(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getKNNQuery(controller, (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getKNNQuery(.KNNQueryRequest) returns (.KNNQueryResponse);</code>
     */
    public abstract void getKNNQuery(
        com.google.protobuf.RpcController controller,
        com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest request,
        com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.michael.endPointCoprocessor.KNNQueryProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getKNNQuery(controller, (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest)request,
            com.google.protobuf.RpcUtil.<com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getKNNQuery(
          com.google.protobuf.RpcController controller,
          com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest request,
          com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.class,
            com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse getKNNQuery(
              com.google.protobuf.RpcController controller,
              com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse getKNNQuery(
          com.google.protobuf.RpcController controller,
          com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.michael.endPointCoprocessor.KNNQueryProto.KNNQueryResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:KNNQueryService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KNNQueryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KNNQueryRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KNNQueryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KNNQueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016KNNQuery.proto\"A\n\017KNNQueryRequest\022\020\n\010l" +
      "atitude\030\001 \002(\001\022\021\n\tlongitude\030\002 \002(\001\022\t\n\001k\030\003 " +
      "\002(\005\"7\n\020KNNQueryResponse\022\020\n\010latitude\030\001 \003(" +
      "\001\022\021\n\tlongitude\030\002 \003(\0012E\n\017KNNQueryService\022" +
      "2\n\013getKNNQuery\022\020.KNNQueryRequest\032\021.KNNQu" +
      "eryResponseB8\n\037com.michael.endPointCopro" +
      "cessorB\rKNNQueryProtoH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_KNNQueryRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_KNNQueryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KNNQueryRequest_descriptor,
              new String[] { "Latitude", "Longitude", "K", });
          internal_static_KNNQueryResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_KNNQueryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KNNQueryResponse_descriptor,
              new String[] { "Latitude", "Longitude", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
