// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RangeQuery.proto

package com.michael.endPointCoprocessor;

public final class RangeQueryProto {
  private RangeQueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RangeQueryRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double startLatitude = 1;
    /**
     * <code>required double startLatitude = 1;</code>
     */
    boolean hasStartLatitude();
    /**
     * <code>required double startLatitude = 1;</code>
     */
    double getStartLatitude();

    // required double startLongitude = 2;
    /**
     * <code>required double startLongitude = 2;</code>
     */
    boolean hasStartLongitude();
    /**
     * <code>required double startLongitude = 2;</code>
     */
    double getStartLongitude();

    // required double endLatitude = 3;
    /**
     * <code>required double endLatitude = 3;</code>
     */
    boolean hasEndLatitude();
    /**
     * <code>required double endLatitude = 3;</code>
     */
    double getEndLatitude();

    // required double endLongitude = 4;
    /**
     * <code>required double endLongitude = 4;</code>
     */
    boolean hasEndLongitude();
    /**
     * <code>required double endLongitude = 4;</code>
     */
    double getEndLongitude();
  }
  /**
   * Protobuf type {@code RangeQueryRequest}
   */
  public static final class RangeQueryRequest extends
      com.google.protobuf.GeneratedMessage
      implements RangeQueryRequestOrBuilder {
    // Use RangeQueryRequest.newBuilder() to construct.
    private RangeQueryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RangeQueryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RangeQueryRequest defaultInstance;
    public static RangeQueryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RangeQueryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RangeQueryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              startLatitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              startLongitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              endLatitude_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              endLongitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.class, com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RangeQueryRequest> PARSER =
        new com.google.protobuf.AbstractParser<RangeQueryRequest>() {
      public RangeQueryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RangeQueryRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RangeQueryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double startLatitude = 1;
    public static final int STARTLATITUDE_FIELD_NUMBER = 1;
    private double startLatitude_;
    /**
     * <code>required double startLatitude = 1;</code>
     */
    public boolean hasStartLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double startLatitude = 1;</code>
     */
    public double getStartLatitude() {
      return startLatitude_;
    }

    // required double startLongitude = 2;
    public static final int STARTLONGITUDE_FIELD_NUMBER = 2;
    private double startLongitude_;
    /**
     * <code>required double startLongitude = 2;</code>
     */
    public boolean hasStartLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double startLongitude = 2;</code>
     */
    public double getStartLongitude() {
      return startLongitude_;
    }

    // required double endLatitude = 3;
    public static final int ENDLATITUDE_FIELD_NUMBER = 3;
    private double endLatitude_;
    /**
     * <code>required double endLatitude = 3;</code>
     */
    public boolean hasEndLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double endLatitude = 3;</code>
     */
    public double getEndLatitude() {
      return endLatitude_;
    }

    // required double endLongitude = 4;
    public static final int ENDLONGITUDE_FIELD_NUMBER = 4;
    private double endLongitude_;
    /**
     * <code>required double endLongitude = 4;</code>
     */
    public boolean hasEndLongitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double endLongitude = 4;</code>
     */
    public double getEndLongitude() {
      return endLongitude_;
    }

    private void initFields() {
      startLatitude_ = 0D;
      startLongitude_ = 0D;
      endLatitude_ = 0D;
      endLongitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStartLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, startLatitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, startLongitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, endLatitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, endLongitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, startLatitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, startLongitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, endLatitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, endLongitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest)) {
        return super.equals(obj);
      }
      com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest other = (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest) obj;

      boolean result = true;
      result = result && (hasStartLatitude() == other.hasStartLatitude());
      if (hasStartLatitude()) {
        result = result && (Double.doubleToLongBits(getStartLatitude())    == Double.doubleToLongBits(other.getStartLatitude()));
      }
      result = result && (hasStartLongitude() == other.hasStartLongitude());
      if (hasStartLongitude()) {
        result = result && (Double.doubleToLongBits(getStartLongitude())    == Double.doubleToLongBits(other.getStartLongitude()));
      }
      result = result && (hasEndLatitude() == other.hasEndLatitude());
      if (hasEndLatitude()) {
        result = result && (Double.doubleToLongBits(getEndLatitude())    == Double.doubleToLongBits(other.getEndLatitude()));
      }
      result = result && (hasEndLongitude() == other.hasEndLongitude());
      if (hasEndLongitude()) {
        result = result && (Double.doubleToLongBits(getEndLongitude())    == Double.doubleToLongBits(other.getEndLongitude()));
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartLatitude()) {
        hash = (37 * hash) + STARTLATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getStartLatitude()));
      }
      if (hasStartLongitude()) {
        hash = (37 * hash) + STARTLONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getStartLongitude()));
      }
      if (hasEndLatitude()) {
        hash = (37 * hash) + ENDLATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getEndLatitude()));
      }
      if (hasEndLongitude()) {
        hash = (37 * hash) + ENDLONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getEndLongitude()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RangeQueryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.class, com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.Builder.class);
      }

      // Construct using com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startLatitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        startLongitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        endLatitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        endLongitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryRequest_descriptor;
      }

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest getDefaultInstanceForType() {
        return com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.getDefaultInstance();
      }

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest build() {
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest buildPartial() {
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest result = new com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startLatitude_ = startLatitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startLongitude_ = startLongitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endLatitude_ = endLatitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endLongitude_ = endLongitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest) {
          return mergeFrom((com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest other) {
        if (other == com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.getDefaultInstance()) return this;
        if (other.hasStartLatitude()) {
          setStartLatitude(other.getStartLatitude());
        }
        if (other.hasStartLongitude()) {
          setStartLongitude(other.getStartLongitude());
        }
        if (other.hasEndLatitude()) {
          setEndLatitude(other.getEndLatitude());
        }
        if (other.hasEndLongitude()) {
          setEndLongitude(other.getEndLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartLatitude()) {
          
          return false;
        }
        if (!hasStartLongitude()) {
          
          return false;
        }
        if (!hasEndLatitude()) {
          
          return false;
        }
        if (!hasEndLongitude()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double startLatitude = 1;
      private double startLatitude_ ;
      /**
       * <code>required double startLatitude = 1;</code>
       */
      public boolean hasStartLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double startLatitude = 1;</code>
       */
      public double getStartLatitude() {
        return startLatitude_;
      }
      /**
       * <code>required double startLatitude = 1;</code>
       */
      public Builder setStartLatitude(double value) {
        bitField0_ |= 0x00000001;
        startLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double startLatitude = 1;</code>
       */
      public Builder clearStartLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startLatitude_ = 0D;
        onChanged();
        return this;
      }

      // required double startLongitude = 2;
      private double startLongitude_ ;
      /**
       * <code>required double startLongitude = 2;</code>
       */
      public boolean hasStartLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double startLongitude = 2;</code>
       */
      public double getStartLongitude() {
        return startLongitude_;
      }
      /**
       * <code>required double startLongitude = 2;</code>
       */
      public Builder setStartLongitude(double value) {
        bitField0_ |= 0x00000002;
        startLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double startLongitude = 2;</code>
       */
      public Builder clearStartLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startLongitude_ = 0D;
        onChanged();
        return this;
      }

      // required double endLatitude = 3;
      private double endLatitude_ ;
      /**
       * <code>required double endLatitude = 3;</code>
       */
      public boolean hasEndLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double endLatitude = 3;</code>
       */
      public double getEndLatitude() {
        return endLatitude_;
      }
      /**
       * <code>required double endLatitude = 3;</code>
       */
      public Builder setEndLatitude(double value) {
        bitField0_ |= 0x00000004;
        endLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double endLatitude = 3;</code>
       */
      public Builder clearEndLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endLatitude_ = 0D;
        onChanged();
        return this;
      }

      // required double endLongitude = 4;
      private double endLongitude_ ;
      /**
       * <code>required double endLongitude = 4;</code>
       */
      public boolean hasEndLongitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double endLongitude = 4;</code>
       */
      public double getEndLongitude() {
        return endLongitude_;
      }
      /**
       * <code>required double endLongitude = 4;</code>
       */
      public Builder setEndLongitude(double value) {
        bitField0_ |= 0x00000008;
        endLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double endLongitude = 4;</code>
       */
      public Builder clearEndLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endLongitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RangeQueryRequest)
    }

    static {
      defaultInstance = new RangeQueryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RangeQueryRequest)
  }

  public interface RangeQueryResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated double latitude = 1;
    /**
     * <code>repeated double latitude = 1;</code>
     */
    java.util.List<Double> getLatitudeList();
    /**
     * <code>repeated double latitude = 1;</code>
     */
    int getLatitudeCount();
    /**
     * <code>repeated double latitude = 1;</code>
     */
    double getLatitude(int index);

    // repeated double longitude = 2;
    /**
     * <code>repeated double longitude = 2;</code>
     */
    java.util.List<Double> getLongitudeList();
    /**
     * <code>repeated double longitude = 2;</code>
     */
    int getLongitudeCount();
    /**
     * <code>repeated double longitude = 2;</code>
     */
    double getLongitude(int index);
  }
  /**
   * Protobuf type {@code RangeQueryResponse}
   */
  public static final class RangeQueryResponse extends
      com.google.protobuf.GeneratedMessage
      implements RangeQueryResponseOrBuilder {
    // Use RangeQueryResponse.newBuilder() to construct.
    private RangeQueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RangeQueryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RangeQueryResponse defaultInstance;
    public static RangeQueryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RangeQueryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RangeQueryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                latitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              latitude_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                latitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                latitude_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                longitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              longitude_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                longitude_ = new java.util.ArrayList<Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                longitude_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          latitude_ = java.util.Collections.unmodifiableList(latitude_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          longitude_ = java.util.Collections.unmodifiableList(longitude_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.class, com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RangeQueryResponse> PARSER =
        new com.google.protobuf.AbstractParser<RangeQueryResponse>() {
      public RangeQueryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RangeQueryResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RangeQueryResponse> getParserForType() {
      return PARSER;
    }

    // repeated double latitude = 1;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private java.util.List<Double> latitude_;
    /**
     * <code>repeated double latitude = 1;</code>
     */
    public java.util.List<Double>
        getLatitudeList() {
      return latitude_;
    }
    /**
     * <code>repeated double latitude = 1;</code>
     */
    public int getLatitudeCount() {
      return latitude_.size();
    }
    /**
     * <code>repeated double latitude = 1;</code>
     */
    public double getLatitude(int index) {
      return latitude_.get(index);
    }

    // repeated double longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private java.util.List<Double> longitude_;
    /**
     * <code>repeated double longitude = 2;</code>
     */
    public java.util.List<Double>
        getLongitudeList() {
      return longitude_;
    }
    /**
     * <code>repeated double longitude = 2;</code>
     */
    public int getLongitudeCount() {
      return longitude_.size();
    }
    /**
     * <code>repeated double longitude = 2;</code>
     */
    public double getLongitude(int index) {
      return longitude_.get(index);
    }

    private void initFields() {
      latitude_ = java.util.Collections.emptyList();
      longitude_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < latitude_.size(); i++) {
        output.writeDouble(1, latitude_.get(i));
      }
      for (int i = 0; i < longitude_.size(); i++) {
        output.writeDouble(2, longitude_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getLatitudeList().size();
        size += dataSize;
        size += 1 * getLatitudeList().size();
      }
      {
        int dataSize = 0;
        dataSize = 8 * getLongitudeList().size();
        size += dataSize;
        size += 1 * getLongitudeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse)) {
        return super.equals(obj);
      }
      com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse other = (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse) obj;

      boolean result = true;
      result = result && getLatitudeList()
          .equals(other.getLatitudeList());
      result = result && getLongitudeList()
          .equals(other.getLongitudeList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getLatitudeCount() > 0) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLatitudeList().hashCode();
      }
      if (getLongitudeCount() > 0) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLongitudeList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RangeQueryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.class, com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.Builder.class);
      }

      // Construct using com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.michael.endPointCoprocessor.RangeQueryProto.internal_static_RangeQueryResponse_descriptor;
      }

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse getDefaultInstanceForType() {
        return com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance();
      }

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse build() {
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse buildPartial() {
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse result = new com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          latitude_ = java.util.Collections.unmodifiableList(latitude_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.latitude_ = latitude_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          longitude_ = java.util.Collections.unmodifiableList(longitude_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse) {
          return mergeFrom((com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse other) {
        if (other == com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance()) return this;
        if (!other.latitude_.isEmpty()) {
          if (latitude_.isEmpty()) {
            latitude_ = other.latitude_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLatitudeIsMutable();
            latitude_.addAll(other.latitude_);
          }
          onChanged();
        }
        if (!other.longitude_.isEmpty()) {
          if (longitude_.isEmpty()) {
            longitude_ = other.longitude_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLongitudeIsMutable();
            longitude_.addAll(other.longitude_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated double latitude = 1;
      private java.util.List<Double> latitude_ = java.util.Collections.emptyList();
      private void ensureLatitudeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          latitude_ = new java.util.ArrayList<Double>(latitude_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public java.util.List<Double>
          getLatitudeList() {
        return java.util.Collections.unmodifiableList(latitude_);
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public int getLatitudeCount() {
        return latitude_.size();
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public double getLatitude(int index) {
        return latitude_.get(index);
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder setLatitude(
          int index, double value) {
        ensureLatitudeIsMutable();
        latitude_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder addLatitude(double value) {
        ensureLatitudeIsMutable();
        latitude_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder addAllLatitude(
          Iterable<? extends Double> values) {
        ensureLatitudeIsMutable();
        super.addAll(values, latitude_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        latitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated double longitude = 2;
      private java.util.List<Double> longitude_ = java.util.Collections.emptyList();
      private void ensureLongitudeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          longitude_ = new java.util.ArrayList<Double>(longitude_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public java.util.List<Double>
          getLongitudeList() {
        return java.util.Collections.unmodifiableList(longitude_);
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public int getLongitudeCount() {
        return longitude_.size();
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public double getLongitude(int index) {
        return longitude_.get(index);
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder setLongitude(
          int index, double value) {
        ensureLongitudeIsMutable();
        longitude_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder addLongitude(double value) {
        ensureLongitudeIsMutable();
        longitude_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder addAllLongitude(
          Iterable<? extends Double> values) {
        ensureLongitudeIsMutable();
        super.addAll(values, longitude_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        longitude_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RangeQueryResponse)
    }

    static {
      defaultInstance = new RangeQueryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RangeQueryResponse)
  }

  /**
   * Protobuf service {@code RangeQueryService}
   */
  public static abstract class RangeQueryService
      implements com.google.protobuf.Service {
    protected RangeQueryService() {}

    public interface Interface {
      /**
       * <code>rpc getRangeQuery(.RangeQueryRequest) returns (.RangeQueryResponse);</code>
       */
      public abstract void getRangeQuery(
              com.google.protobuf.RpcController controller,
              com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest request,
              com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RangeQueryService() {
        @Override
        public  void getRangeQuery(
            com.google.protobuf.RpcController controller,
            com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest request,
            com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse> done) {
          impl.getRangeQuery(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getRangeQuery(controller, (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getRangeQuery(.RangeQueryRequest) returns (.RangeQueryResponse);</code>
     */
    public abstract void getRangeQuery(
        com.google.protobuf.RpcController controller,
        com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest request,
        com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.michael.endPointCoprocessor.RangeQueryProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getRangeQuery(controller, (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest)request,
            com.google.protobuf.RpcUtil.<com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getRangeQuery(
          com.google.protobuf.RpcController controller,
          com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest request,
          com.google.protobuf.RpcCallback<com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.class,
            com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse getRangeQuery(
              com.google.protobuf.RpcController controller,
              com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse getRangeQuery(
          com.google.protobuf.RpcController controller,
          com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.michael.endPointCoprocessor.RangeQueryProto.RangeQueryResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:RangeQueryService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RangeQueryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RangeQueryRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RangeQueryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RangeQueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RangeQuery.proto\"m\n\021RangeQueryRequest\022" +
      "\025\n\rstartLatitude\030\001 \002(\001\022\026\n\016startLongitude" +
      "\030\002 \002(\001\022\023\n\013endLatitude\030\003 \002(\001\022\024\n\014endLongit" +
      "ude\030\004 \002(\001\"9\n\022RangeQueryResponse\022\020\n\010latit" +
      "ude\030\001 \003(\001\022\021\n\tlongitude\030\002 \003(\0012M\n\021RangeQue" +
      "ryService\0228\n\rgetRangeQuery\022\022.RangeQueryR" +
      "equest\032\023.RangeQueryResponseB:\n\037com.micha" +
      "el.endPointCoprocessorB\017RangeQueryProtoH" +
      "\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RangeQueryRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RangeQueryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RangeQueryRequest_descriptor,
              new String[] { "StartLatitude", "StartLongitude", "EndLatitude", "EndLongitude", });
          internal_static_RangeQueryResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RangeQueryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RangeQueryResponse_descriptor,
              new String[] { "Latitude", "Longitude", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
